### PR TITLE
Use `main` primary branch

### PR DESCRIPTION
**Pull request by JamyGolden**
Are you ok with me merging this and adjusting the repo settings to use `main` primary branch? We're using main on the other repos.

### CODE REVIEW

**Comment by tani** [comment]
Sure!

**Comment by tani** [comment]
However, I have no privilege to modify the default branch. Further, I would like to change to the right top short description of the front project page. Would you mind assigning the higher privilege to me.?

**Comment by JamyGolden** [comment]
Currently the privileged of the github groups assigned to the repos are at "maintainer" level, but I'll change it to admin privileges for you while you're still setting the repo up properly.

**Comment by tani** [comment]
Thank you so much. Now the default branch is `main`. Done.

**Pull request merged**
